name: Suggestion Box
description: Create a report to help us improve
title: "[Suggestion]: "
labels: ["bug", "suggestion", "advice"]
body:
  - type: input
    id: summary
    attributes:
      label: Suggestion Summary
      description: "Provide a concise, one-sentence summary of the bug."
      placeholder: "e.g., User login fails when using special characters in password."
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Give a detailed description of the issue. Include steps to reproduce it."
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: "What is currently happening?"
      placeholder: "Describe the unexpected behavior you are observing."
    validations:
      required: false

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: "What did you expect to happen instead?"
      placeholder: "Describe what the correct behavior should be."
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: "If applicable, add screenshots to help explain your problem. You can drag and drop images here."
    validations:
      required: false